package: binstar-build
engine:
  - python=2.7
platform:
  - linux-64
  - osx-64

install:
  - conda install binstar
  - pip install coverage mock

script:
  - touch build.sh # FIX: for conda issue
  - conda build .

build_targets: conda
