package: binstar-build
engine:
  - python=2.7
  - python=3.4
platform:
  - linux-64
  - osx-64
  - win-64

install:
  - conda install anaconda-client pip setuptools
  - pip install coverage mock

test:
  - python setup.py develop
  - python -m unittest discover -v


script:
  - conda build conda.recipe

build_targets: conda

quiet: True