FROM: continuumIO/conda_builder_linux
RUN yum install -y patch subversion

MAINTAINER Peter Steinberg <psteinberg@continuum.io>

RUN conda install curl openssl zlib

RUN conda config --set always_yes true && \
    conda config --set anaconda_upload false && \
    conda config --add channels binstar
RUN conda install conda-build jinja2 anaconda-client psutil anaconda-build llvm
RUN anaconda config --set url https://api.anaconda.org

RUN export CFLAGS="${CFLAGS} -m32"
RUN export CXXFLAGS="${CXXFLAGS} -m32"
RUN echo >> ~/.bashrc
RUN echo 'export CFLAGS="\${CFLAGS} -m32"' >> ~/.bashrc
RUN echo 'export CXXFLAGS="\${CXXFLAGS} -m32"' >> ~/.bashrc
RUN export CONDA_FORCE_32BIT=1
RUN echo 'export CONDA_FORCE_32BIT=1' >> ~/.bashrc

