{% set data = load_setuptools()%}
package:
  name: binstar-build
  version: {{data.get('version')}}

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON make_version.py
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - binstar

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
